# Generated by Django 5.2.12 on 2026-03-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Evento')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Horário')),
                ('categoria', models.CharField(choices=[('culto', 'Culto Geral'), ('ebd', 'Escola Bíblica'), ('reuniao', 'Reunião de Liderança'), ('social', 'Ação Social')], default='culto', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Banner/Flyer')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade_nome', models.CharField(max_length=100, verbose_name='Unidade/Igreja')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_hora'],
            },
        ),
    ]
