# Generated by Django 5.2.12 on 2026-03-31 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Unidade')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('tipo', models.CharField(choices=[('SEDE', 'Sede'), ('FILIAL', 'Congregação / Filial'), ('PONTO', 'Ponto de Pregação')], default='FILIAL', max_length=10)),
                ('data_fundacao', models.DateField(blank=True, null=True, verbose_name='Data de Fundação')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade Sentada')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativa'), ('REFORMA', 'Em Reforma'), ('INATIVA', 'Inativa / Fechada')], default='ATIVO', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Breve Histórico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='evento',
            name='unidade_nome',
        ),
        migrations.AddField(
            model_name='evento',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='igrejas.igreja', verbose_name='Unidade/Igreja'),
        ),
    ]
