# Generated by Django 5.2.12 on 2026-03-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('visitante', 'Visitante'), ('membro', 'Membro'), ('congregado', 'Congregado'), ('kids', 'Kids'), ('pastor', 'Pastor'), ('presbitero', 'Presbítero'), ('evangelista', 'Evangelista'), ('missionario', 'Missionário')], max_length=20)),
                ('igreja_origem', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo')], max_length=20)),
                ('status_acompanhamento', models.CharField(blank=True, choices=[('novo_convertido', 'Novo convertido'), ('em_discipulado', 'Em discipulado'), ('desigrejado', 'Desigrejado'), ('visitante_recorrente', 'Visitante recorrente'), ('nenhum', 'Nenhum')], max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.endereco')),
            ],
        ),
    ]
