# Generated by Django 5.2.12 on 2026-03-25 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='membro_desta_igreja',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ministerio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='igreja_origem',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='status_acompanhamento',
            field=models.CharField(blank=True, choices=[('novo', 'Novo convertido'), ('discipulado', 'Em discipulado'), ('recorrente', 'Visitante recorrente'), ('desigrejado', 'Desigrejado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('membro', 'Membro'), ('congregado', 'Congregado'), ('kids', 'Kids'), ('pastor', 'Pastor'), ('presbitero', 'Presbítero'), ('evangelista', 'Evangelista'), ('missionario', 'Missionário')], max_length=20),
        ),
    ]
