# Generated by Django 5.2.12 on 2026-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_criado_em_pessoa_membro_desta_igreja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
