# Generated by Django 5.2.12 on 2026-04-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0002_igreja_remove_evento_unidade_nome_evento_igreja'),
        ('pessoas', '0003_pessoa_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='igrejas.igreja'),
        ),
    ]
