# Generated by Django 5.2.12 on 2026-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_pessoa_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('membro', 'Membro'), ('congregado', 'Congregado'), ('kids', 'Kids'), ('obreiro', 'Obreiro'), ('pastor', 'Pastor'), ('presbitero', 'Presbítero'), ('evangelista', 'Evangelista'), ('missionario', 'Missionário')], max_length=20),
        ),
    ]
