# Generated by Django 5.2.12 on 2026-04-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('igrejas', '0003_igreja_pastor'),
        ('pessoas', '0005_alter_pessoa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail de Acesso')),
                ('nome_solicitante', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('perfil', models.CharField(choices=[('presidente', 'Pastor Presidente / Diretoria'), ('pastor_unidade', 'Pastor de Unidade'), ('tesoureiro', 'Tesoureiro (Finanças da Unidade)'), ('lider_departamento', 'Líder de Departamento'), ('midia', 'Mídia (Cultos Locais)')], max_length=30)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Aprovação)'), ('ATIVO', 'Ativo'), ('INATIVO', 'Inativo / Bloqueado')], default='PENDENTE', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_sistema_groups', to='auth.group', verbose_name='groups')),
                ('igreja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='igrejas.igreja')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_acesso', to='pessoas.pessoa')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_sistema_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário do Sistema',
                'verbose_name_plural': 'Usuários do Sistema',
                'db_table': 'usuarios_sistema',
            },
        ),
    ]
