# Generated by Django 5.2.12 on 2026-04-14 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultos', '0002_culto_cor_personalizada_culto_estilo_card'),
        ('igrejas', '0003_igreja_pastor'),
        ('pessoas', '0005_alter_pessoa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('vencimento_dia', models.IntegerField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=50)),
                ('chave_pix', models.CharField(max_length=255)),
                ('igreja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('URGENTE', 'Urgente'), ('NECESSARIO', 'Necessário'), ('MELHORIA', 'Melhoria')], default='NECESSARIO', max_length=20)),
                ('observacao', models.TextField()),
                ('orcamento_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('categoria', models.CharField(choices=[('DIZIMO', 'Dízimo'), ('OFERTA', 'Oferta'), ('MISSIONARIA', 'Oferta Missionária'), ('AVULSA', 'Oferta Avulsa'), ('OUTROS', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('origem_whatsapp', models.BooleanField(default=False)),
                ('culto_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultos.culto')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='igrejas.igreja')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa')),
            ],
        ),
    ]
