# Generated by Django 5.2.12 on 2026-04-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('igrejas', '0003_igreja_pastor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(default='Outros', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('recorrencia', models.CharField(choices=[('unica', 'Única'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
        ),
        migrations.DeleteModel(
            name='ContaFixa',
        ),
    ]
