# Generated by Django 5.2.12 on 2026-04-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_obrigacao_delete_contafixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrigacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], default='SAIDA', max_length=10),
        ),
    ]
