# Generated by Django 5.2.12 on 2026-04-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrigacao',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
