# Generated by Django 5.2.12 on 2026-05-27 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006 autorizado por'),
        ('igrejas', '0003_igreja_pastor'),
        ('pessoas', '0005_alter_pessoa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_pagamento_id', models.CharField(db_index=True, help_text='Chave que o n8n usa para identificar o pagamento.', max_length=64, unique=True, verbose_name='ID Mercado Pago')),
                ('pix_code', models.TextField(verbose_name='Código Copia e Cola')),
                ('pix_qr_base64', models.TextField(verbose_name='QR Code (base64)')),
                ('tipo', models.CharField(choices=[('DIZIMO', 'Dízimo'), ('OFERTA', 'Oferta'), ('MISSIONARIA', 'Oferta Missionária'), ('AVULSA', 'Construção / Infraestrutura')], default='OFERTA', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('approved', 'Aprovado'), ('cancelled', 'Cancelado'), ('rejected', 'Rejeitado'), ('refunded', 'Estornado')], default='pending', max_length=20)),
                ('pagador_nome', models.CharField(blank=True, default='', max_length=150)),
                ('pagador_email', models.EmailField(blank=True, default='', max_length=254)),
                ('pagador_cpf', models.CharField(blank=True, default='', max_length=11, verbose_name='CPF (só números)')),
                ('pagador_telefone', models.CharField(blank=True, default='', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_pix', to='igrejas.igreja')),
            ],
            options={
                'verbose_name': 'Pagamento PIX',
                'verbose_name_plural': 'Pagamentos PIX',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='membro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='pessoas.pessoa', verbose_name='Membro / Doador'),
        ),
        migrations.AddField(
            model_name='pagamentopix',
            name='movimentacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento_pix_origem', to='financeiro.movimentacao'),
        ),
    ]
