# Generated by Django 5.2.12 on 2026-04-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igrejas', '0003_igreja_pastor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome do evento ou Tema do culto', max_length=200)),
                ('tipo', models.CharField(choices=[('culto_domingo', 'Culto de Domingo'), ('doutrina', 'Culto de Doutrina'), ('oracao', 'Reunião de Oração'), ('celula', 'Célula'), ('ensaio', 'Ensaio do Louvor'), ('evento_especial', 'Evento Especial'), ('outros', 'Outros')], default='culto_domingo', max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('pregador_palestrante', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição livre para eventos especiais', null=True)),
                ('local', models.CharField(default='Templo Principal', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultos', to='igrejas.igreja')),
            ],
            options={
                'verbose_name': 'Culto/Evento',
                'verbose_name_plural': 'Cultos e Eventos',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
