# Generated by Django 5.2.12 on 2026-04-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culto',
            name='cor_personalizada',
            field=models.CharField(default='#2563eb', help_text='Cor em Hexadecimal', max_length=7),
        ),
        migrations.AddField(
            model_name='culto',
            name='estilo_card',
            field=models.CharField(choices=[('solido', 'Cor Sólida'), ('gradiente', 'Gradiente Animado'), ('desenhado', 'Padrão Geométrico')], default='solido', max_length=20),
        ),
    ]
